#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HookADuck
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HookADuck")]
	public partial class HookADuckDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPrize(Prize instance);
    partial void UpdatePrize(Prize instance);
    partial void DeletePrize(Prize instance);
    #endregion
		
		public HookADuckDataClassesDataContext() : 
				base(global::HookADuck.Properties.Settings.Default.HookADuckConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public HookADuckDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HookADuckDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HookADuckDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HookADuckDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Duck> Ducks
		{
			get
			{
				return this.GetTable<Duck>();
			}
		}
		
		public System.Data.Linq.Table<Prize> Prizes
		{
			get
			{
				return this.GetTable<Prize>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckDuck")]
		public ISingleResult<CheckDuckResult> CheckDuck([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Barcode", DbType="NChar(20)")] string barcode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), barcode);
			return ((ISingleResult<CheckDuckResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdatePrize")]
		public int UpdatePrize([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckPrize")]
		public ISingleResult<CheckPrizeResult> CheckPrize([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<CheckPrizeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllDucks")]
		public ISingleResult<GetAllDucksResult> GetAllDucks()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllDucksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllPrizes")]
		public ISingleResult<GetAllPrizesResult> GetAllPrizes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllPrizesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDuck")]
		public ISingleResult<GetDuckResult> GetDuck([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetDuckResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPrize")]
		public ISingleResult<GetPrizeResult> GetPrize([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetPrizeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateDuck")]
		public int UpdateDuck([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Barcode", DbType="NChar(20)")] string barcode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), barcode);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ducks")]
	public partial class Duck
	{
		
		private int _ID;
		
		private string _Barcode;
		
		private string _Name;
		
		private System.Nullable<int> _PrizeID;
		
		private int _Scanned;
		
		public Duck()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrizeID", DbType="Int")]
		public System.Nullable<int> PrizeID
		{
			get
			{
				return this._PrizeID;
			}
			set
			{
				if ((this._PrizeID != value))
				{
					this._PrizeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scanned", DbType="Int NOT NULL")]
		public int Scanned
		{
			get
			{
				return this._Scanned;
			}
			set
			{
				if ((this._Scanned != value))
				{
					this._Scanned = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prizes")]
	public partial class Prize : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Prize1;
		
		private System.Nullable<int> _Won;
		
		private string _Image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPrize1Changing(string value);
    partial void OnPrize1Changed();
    partial void OnWonChanging(System.Nullable<int> value);
    partial void OnWonChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    #endregion
		
		public Prize()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Prize", Storage="_Prize1", DbType="NChar(100)")]
		public string Prize1
		{
			get
			{
				return this._Prize1;
			}
			set
			{
				if ((this._Prize1 != value))
				{
					this.OnPrize1Changing(value);
					this.SendPropertyChanging();
					this._Prize1 = value;
					this.SendPropertyChanged("Prize1");
					this.OnPrize1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Won", DbType="Int")]
		public System.Nullable<int> Won
		{
			get
			{
				return this._Won;
			}
			set
			{
				if ((this._Won != value))
				{
					this.OnWonChanging(value);
					this.SendPropertyChanging();
					this._Won = value;
					this.SendPropertyChanged("Won");
					this.OnWonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NChar(20)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class CheckDuckResult
	{
		
		private int _ID;
		
		private string _Barcode;
		
		private string _Name;
		
		private System.Nullable<int> _PrizeID;
		
		private int _Scanned;
		
		public CheckDuckResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrizeID", DbType="Int")]
		public System.Nullable<int> PrizeID
		{
			get
			{
				return this._PrizeID;
			}
			set
			{
				if ((this._PrizeID != value))
				{
					this._PrizeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scanned", DbType="Int NOT NULL")]
		public int Scanned
		{
			get
			{
				return this._Scanned;
			}
			set
			{
				if ((this._Scanned != value))
				{
					this._Scanned = value;
				}
			}
		}
	}
	
	public partial class CheckPrizeResult
	{
		
		private System.Nullable<int> _Won;
		
		public CheckPrizeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Won", DbType="Int")]
		public System.Nullable<int> Won
		{
			get
			{
				return this._Won;
			}
			set
			{
				if ((this._Won != value))
				{
					this._Won = value;
				}
			}
		}
	}
	
	public partial class GetAllDucksResult
	{
		
		private int _ID;
		
		private string _Barcode;
		
		private string _Name;
		
		private System.Nullable<int> _PrizeID;
		
		private int _Scanned;
		
		public GetAllDucksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrizeID", DbType="Int")]
		public System.Nullable<int> PrizeID
		{
			get
			{
				return this._PrizeID;
			}
			set
			{
				if ((this._PrizeID != value))
				{
					this._PrizeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scanned", DbType="Int NOT NULL")]
		public int Scanned
		{
			get
			{
				return this._Scanned;
			}
			set
			{
				if ((this._Scanned != value))
				{
					this._Scanned = value;
				}
			}
		}
	}
	
	public partial class GetAllPrizesResult
	{
		
		private int _ID;
		
		private string _Prize;
		
		private System.Nullable<int> _Won;
		
		private string _Image;
		
		public GetAllPrizesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prize", DbType="NChar(100)")]
		public string Prize
		{
			get
			{
				return this._Prize;
			}
			set
			{
				if ((this._Prize != value))
				{
					this._Prize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Won", DbType="Int")]
		public System.Nullable<int> Won
		{
			get
			{
				return this._Won;
			}
			set
			{
				if ((this._Won != value))
				{
					this._Won = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NChar(20)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
	}
	
	public partial class GetDuckResult
	{
		
		private int _ID;
		
		private string _Barcode;
		
		private string _Name;
		
		private System.Nullable<int> _PrizeID;
		
		private int _Scanned;
		
		public GetDuckResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrizeID", DbType="Int")]
		public System.Nullable<int> PrizeID
		{
			get
			{
				return this._PrizeID;
			}
			set
			{
				if ((this._PrizeID != value))
				{
					this._PrizeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scanned", DbType="Int NOT NULL")]
		public int Scanned
		{
			get
			{
				return this._Scanned;
			}
			set
			{
				if ((this._Scanned != value))
				{
					this._Scanned = value;
				}
			}
		}
	}
	
	public partial class GetPrizeResult
	{
		
		private int _ID;
		
		private string _Prize;
		
		private System.Nullable<int> _Won;
		
		private string _Image;
		
		public GetPrizeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prize", DbType="NChar(100)")]
		public string Prize
		{
			get
			{
				return this._Prize;
			}
			set
			{
				if ((this._Prize != value))
				{
					this._Prize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Won", DbType="Int")]
		public System.Nullable<int> Won
		{
			get
			{
				return this._Won;
			}
			set
			{
				if ((this._Won != value))
				{
					this._Won = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NChar(20)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
